### PR TITLE
[RUM-23969][FEATURE] added UA collector

### PR DESCRIPTION
**Pull request by robertdumitrescu**

### CODE REVIEW

**Comment by MalcolmSmithUK** [comment]
@robertdumitrescu Code looks good.  I'd suggest we add it to the 'default' collectors so that all instrumentations benefit from this 'out-of-the-box'.  What do you reckon?

**Comment by robertdumitrescu** [comment]
@MalcolmSmithUK I agree, we should add it as default and then take it out when this feature was developed specifically for certain use cases.

**Review by MalcolmSmithUK — APPROVED** [review]

**Comment by MalcolmSmithUK** [comment]
Looks good.

**Comment by Ian-Hi** [comment]
Approved

**Review by Ian-Hi — APPROVED** [review]
Approved

**Pull request merged**
